### ISSUE TITLE
Error in installation by conda

### ISSUE THREAD

**Issue by lorenalorenzo** [harris-2374/THEx#2]
I am trying to install the software in linux through miniconda3 and there is an issue when running:
`conda install thex -c ajharris_2374`
It gets stuck in this but doesn't achieve to install anything. I have tried in several ways but I presume there is a problem with the binaries. 
Sorry for the inconveniences and many thanks in advance.

**Comment by harris-2374** [comment]
Hi @lorenalorenzo,

I am sorry to hear you are having issues getting THEx to install. I have not had this issue raised before, so I am unsure what the root cause is. THEx has several dependencies, so there could be a slowdown in computing the environment on your system. I am working to provide a Singularity/Docker container and reduce the number of dependencies for THEx, ideally resolving any installation issues. Once I have this up and working, I will respond to this issue and let you know!

Thanks,
Andrew

**Comment by lorenalorenzo** [comment]
Hi @harris-2374 , many thanks for your answer. 
We managed to solve this issue by creating a ylm file with the dependencies needed where the conda environment is going to be activated. 

However, I have another issue with the input, as we were going to use Cactus free-reference whole genome assemblies alignment but we have read in another issue posted here that Thex is recommended for reference-based data. Is there a way of using Cactus alignment or may you recommend using minimap2 assemblies alignment instead?

Sorry for the inconvenience and thanks in advance,
Lorena

**Comment by harris-2374** [comment]
Hi Lorena,

I am glad you were able to find a solution to your installation issue. 

As for your input, THEx currently assumes you are providing a reference-based alignment. I believe there is a function within the HAL tools of the ComparativeGenomicsToolkit that can convert the HAL alignment to a referenced FASTA file (i.e., hal2fasta), so you should be able to use your HAL alignment to get there. If not, then I would recommend using minimap2.

Best,
Andrew

**Comment by lorenalorenzo** [comment]
Resolved by adding a .yml file with the dependencies needed for running thex via conda.
